[project]
name = "rdn"
version = "0.0.1"
authors = [
  { name="Janko Petkovic", email="petkojan@uni-bonn.de" },
]
description = "Modules used for the code in 'push-and-pull' paper."
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "ipykernel",
    "fides",
    "matplotlib",
    "pypesto",
    "torch",
    "statsmodels",
    "scikit_posthocs",
    "palettable",
    "scikit-image",
    "marimo>=0.23.16",
]

[build-system]
requires = ["uv_build>0.11.23, <0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.16.1",
]

[project.urls]
"Homepage" = "https://github.com/janko-petkovic/push-pull-code"

[tool.ruff]
line-length = 79
format.skip-magic-trailing-comma = true
lint.isort.split-on-trailing-comma = false
